### ISSUE TITLE
Clean project doesn't work without installed dev dependencies

### ISSUE THREAD

**Issue by astorozhevsky** [RonasIT/laravel-empty-project#11]
**Steps to reproduce:**

1. Clone the repository
2. Change [the line](https://github.com/RonasIT/laravel-empty-project/blob/development/Dockerfile#L10) to `composer install --no-dev`
3. Build and run docker image
4. Make any HTTP request to API

**Actual result:**

The error occurs:

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/11055414/172358654-96e40b99-0451-40c2-a05d-8e8bef36f19f.png">

```
[previous exception] [object] (ReflectionException(code: -1): Class \"RonasIT\\Support\\AutoDoc\\Http\\Middleware\\AutoDocMiddleware\" does not exist at /app/vendor/laravel/framework/src/Illuminate/Container/Container.php:875)
[stacktrace]
#0 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(875): ReflectionClass->__construct('RonasIT\\\\Support...')
#1 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\\Container\\Container->build('RonasIT\\\\Support...')
#2 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\\Container\\Container->resolve('RonasIT\\\\Support...', Array, true)
#3 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\\Foundation\\Application->resolve('RonasIT\\\\Support...', Array)
#4 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\\Container\\Container->make('RonasIT\\\\Support...', Array)
#5 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(206): Illuminate\\Foundation\\Application->make('RonasIT\\\\Support...')
#6 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(180): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#7 /app/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#8 {main}
"} 
```

**Expected result:**

Clean project should work without installed dev dependencies.

**Comment by DenTray** [comment]
@astorozhevsky fixed
